[package]
name = "xemanh"
version = "0.1.10"
edition = "2024"
description = "Lightweight image viewer"
authors = ["hoangphuctv"]
readme = "README.md"
keywords = ["image", "viewer", "photo"]
categories = ["multimedia"]

[dependencies]
macroquad = "0.4.16"
image = { version = "0.24", default-features = false, features = ["jpeg", "png", "bmp", "gif"] }
kamadak-exif = "0.6"

[target.'cfg(target_os = "macos")'.dependencies]
objc = { version = "0.2", package = "objc-rs" }
