[package]
name = "xemanh-set-default"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
md-5 = "0.10"
winapi = { version = "0.3", features = [
    "winbase",
    "winreg",
    "wincrypt",
    "bcrypt",
    "winnt",
    "processthreadsapi",
    "handleapi",
    "sddl",
    "sysinfoapi",
    "timezoneapi",
    "securitybaseapi",
    "minwinbase",
    "minwindef",
] }
